[project]
name = 'succotash_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.allowance_wallet]
path = 'contracts/allowance_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.mini_deposit]
path = 'contracts/mini_deposit.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_user_wallet]
path = 'contracts/multi_user_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_quota]
path = 'contracts/storage_quota.clar'
clarity_version = 2
epoch = 2.5

[contracts.versioned_storage]
path = 'contracts/versioned_storage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
